
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Antonio
 */
public class Doktor extends javax.swing.JFrame {

    /**
     * Creates new form Doktor
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public Doktor() {
        initComponents();
        conn=MySqlConnector.ConnectDB();
        
    }
    ///////////////////UZIMA PODATKE IZ TABLICE LIJEKOVA/////////////////////////////////////
    private void tabZaLijekove(){
    String sql="SELECT ID, Ime, Doza, datum FROM lijekovi where zdravstveni_broj_p=? ";
    try{
    pst=conn.prepareStatement(sql);
    pst.setString(1, traziPacTxt.getText());
    rs=pst.executeQuery();
    tabZaLijekove.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }}
    //UZIMA PODATKE IZ TABLICE UPUTNICA/////////////////////////////// 
    public void tabZaUputnice(){
    String sql="SELECT *FROM uputnice where zdravstveni_broj_pac=? ";
    try{
    pst=conn.prepareStatement(sql);
    pst.setString(1, traziPacTxt.getText());
    rs=pst.executeQuery();
    tabZaUputnice.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }}
    ////////////////NA KLIK DIJAGNOZU UCITAVA///////////////////////////
    private void tabZaDijag(){
    String sql="SELECT ID,Kod,Dijagnoza,Datum FROM dijagnoze where zdravstveni_broj_pa=? ";
    try{
    pst=conn.prepareStatement(sql);
    pst.setString(1, traziPacTxt.getText());
    rs=pst.executeQuery();
    tabZaDijagnozu.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }}
    //////////////////////////////IZ ZDR BROJA UZIMA SVE PODATKE////////////////////
    private void imePrez(){
    try{
        String sql="SELECT *FROM pacijenti where zdravstveni_broj=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, traziPacTxt.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Ime");
                imePac.setText(add1);
                String add2=rs.getString("Prezime");
                prezPac.setText(add2);
                String add3=rs.getString("Dat_rod");
                datPac.setText(add3);              
                String add5=rs.getString("Kontakt");
                konPac.setText(add5);
                String add6=rs.getString("Spol");
                spolPac.setText(add6);
                
            }
            
            
    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }}
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        traziPacTxt = new javax.swing.JTextField();
        traziPacDok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabZaLijekove = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabZaUputnice = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabZaDijagnozu = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        konPac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prezPac = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        datPac = new javax.swing.JTextField();
        imePac = new javax.swing.JTextField();
        spolPac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        otvoriDijag = new javax.swing.JButton();
        otvoriLijek = new javax.swing.JButton();
        otvoriUputnicu = new javax.swing.JButton();
        brisiDijag = new javax.swing.JButton();
        brisiLijek = new javax.swing.JButton();
        brisiUputnicu = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        traziPacDok.setText("Traži");
        traziPacDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traziPacDokActionPerformed(evt);
            }
        });

        jLabel3.setText("Lijekovi");

        jLabel4.setText("Uputnica");

        tabZaLijekove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabZaLijekove);

        tabZaUputnice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabZaUputnice);

        jLabel1.setText("Zdravstveni broj");

        jLabel6.setText("Dijagnoze");

        tabZaDijagnozu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabZaDijagnozu);

        konPac.setEditable(false);

        jLabel5.setText("Prezime:");

        jLabel9.setText("Kontakt:");

        prezPac.setEditable(false);

        jLabel10.setText("Spol:");

        jLabel7.setText("Datum rođenja:");

        datPac.setEditable(false);

        imePac.setEditable(false);

        spolPac.setEditable(false);

        jLabel2.setText("Ime:");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spolPac, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(konPac, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(datPac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prezPac, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imePac, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(prezPac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(datPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(spolPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(konPac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(prezPac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(datPac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(imePac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(spolPac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        otvoriDijag.setText("Dodaj dijagnozu");
        otvoriDijag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otvoriDijagMouseClicked(evt);
            }
        });

        otvoriLijek.setText("Dodaj lijek");
        otvoriLijek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otvoriLijekMouseClicked(evt);
            }
        });

        otvoriUputnicu.setText("Dodaj uputnicu");
        otvoriUputnicu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                otvoriUputnicuMousePressed(evt);
            }
        });

        brisiDijag.setText("jButton5");
        brisiDijag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brisiDijagActionPerformed(evt);
            }
        });

        brisiLijek.setText("jButton6");
        brisiLijek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brisiLijekActionPerformed(evt);
            }
        });

        brisiUputnicu.setText("jButton7");
        brisiUputnicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brisiUputnicuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(traziPacDok)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(traziPacTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(otvoriDijag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(otvoriLijek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(otvoriUputnicu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brisiDijag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brisiUputnicu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brisiLijek, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(traziPacDok)
                            .addComponent(traziPacTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(otvoriDijag)
                        .addGap(18, 18, 18)
                        .addComponent(otvoriLijek)
                        .addGap(18, 18, 18)
                        .addComponent(otvoriUputnicu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(568, 568, 568)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(brisiDijag)
                            .addComponent(brisiLijek))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(brisiUputnicu))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/////////////////////////NA PRITISAK GUMBA PRETRAZUJE SVE O PACIJENTU/////////////////////
    private void traziPacDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traziPacDokActionPerformed
        // TODO add your handling code here:
        imePrez();
        tabZaLijekove();
        tabZaUputnice();
        tabZaDijag();
    }//GEN-LAST:event_traziPacDokActionPerformed

    private void otvoriDijagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otvoriDijagMouseClicked
        // TODO add your handling code here:
        Dijagnoze obj1= new Dijagnoze();
        obj1.setVisible(true);
    }//GEN-LAST:event_otvoriDijagMouseClicked

    private void otvoriLijekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otvoriLijekMouseClicked
        // TODO add your handling code here:
        Lijekovi obj2= new Lijekovi();
        obj2.setVisible(true);
    }//GEN-LAST:event_otvoriLijekMouseClicked

    private void otvoriUputnicuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otvoriUputnicuMousePressed
        // TODO add your handling code here:
        Uputnice obj3= new Uputnice();
        obj3.setVisible(true);                       
    }//GEN-LAST:event_otvoriUputnicuMousePressed

    private void brisiDijagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brisiDijagActionPerformed
        // TODO add your handling code here:
        try{
      int stupac=tabZaDijagnozu.getSelectedRow();
            String Tbl=(tabZaDijagnozu.getModel().getValueAt(stupac,0).toString());
            String sql="SELECT * FROM dijagnoze WHERE ID="+Tbl+"";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery(); 
            if(rs.next()){
           int id=rs.getInt("ID");     
           String Query = "DELETE FROM dijagnoze WHERE ID = ?";
                    pst=conn.prepareStatement(Query);
                    pst.setInt(1,id);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Obrisano");
                    tabZaDijag(); 
            }     
        }catch(Exception e){
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_brisiDijagActionPerformed

    private void brisiLijekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brisiLijekActionPerformed
        // TODO add your handling code here:
            try{
      int stupac=tabZaLijekove.getSelectedRow();
            String Tbl=(tabZaLijekove.getModel().getValueAt(stupac,0).toString());
            String sql="SELECT * FROM lijekovi WHERE ID="+Tbl+"";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery(); 
            if(rs.next()){
           int id=rs.getInt("ID");     
           String Query = "DELETE FROM lijekovi WHERE ID = ?";
                    pst=conn.prepareStatement(Query);
                    pst.setInt(1,id);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Obrisano");
                    tabZaLijekove(); 
            }     
        }catch(Exception e){
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(null,e);
    }//GEN-LAST:event_brisiLijekActionPerformed
    }
    private void brisiUputnicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brisiUputnicuActionPerformed
        // TODO add your handling code here:
             try{
      int stupac=tabZaUputnice.getSelectedRow();
            String Tbl=(tabZaUputnice.getModel().getValueAt(stupac,0).toString());
            String sql="SELECT * FROM uputnice WHERE ID="+Tbl+"";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery(); 
            if(rs.next()){
           int id=rs.getInt("ID");     
           String Query = "DELETE FROM uputnice WHERE ID = ?";
                    pst=conn.prepareStatement(Query);
                    pst.setInt(1,id);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Obrisano");
                    tabZaUputnice(); 
            }     
        }catch(Exception e){
            e.printStackTrace(System.out);
            JOptionPane.showMessageDialog(null,e);
    }
        
        
    }//GEN-LAST:event_brisiUputnicuActionPerformed
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doktor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brisiDijag;
    private javax.swing.JButton brisiLijek;
    private javax.swing.JButton brisiUputnicu;
    private javax.swing.JTextField datPac;
    private javax.swing.JTextField imePac;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField konPac;
    private javax.swing.JButton otvoriDijag;
    private javax.swing.JButton otvoriLijek;
    private javax.swing.JButton otvoriUputnicu;
    private javax.swing.JTextField prezPac;
    private javax.swing.JTextField spolPac;
    private javax.swing.JTable tabZaDijagnozu;
    private javax.swing.JTable tabZaLijekove;
    private javax.swing.JTable tabZaUputnice;
    private javax.swing.JButton traziPacDok;
    private javax.swing.JTextField traziPacTxt;
    // End of variables declaration//GEN-END:variables
}

