import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.Position;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author Antonio
 */
public class Sestra extends javax.swing.JFrame {
    /**
     * Creates new form Sestra
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public Sestra() {
        
        initComponents();
        conn=MySqlConnector.ConnectDB();
        osvjTabZap();
        osvjTabPac();
        }
        ////////////////NA KLIK UPUTNICE UCITAVA///////////////////////////
    private void tabZaUputnice(){
    String sql="SELECT *FROM uputnice where zdravstveni_broj_pac=? ";
    try{
    pst=conn.prepareStatement(sql);
    pst.setString(1, traziPac.getText());
    rs=pst.executeQuery();
    tabZaUputnice.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
    e.printStackTrace(System.out);
    }}
        ////////////////NA KLIK DIJAGNOZU UCITAVA///////////////////////////
    private void tabZaDijag(){
    String sql="SELECT *FROM dijagnoze where zdravstveni_broj_pa=? ";
    try{
    pst=conn.prepareStatement(sql);
    pst.setString(1, traziPac.getText());
    rs=pst.executeQuery();
    tabZaDijag.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
    e.printStackTrace(System.out);
    }}
     ////////////////NA KLIK LIJEKOVE UCITAVA///////////////////////////
    private void tabZaLijekove(){
    String sql="SELECT *FROM lijekovi where zdravstveni_broj_p=? ";
    try{
    pst=conn.prepareStatement(sql);
    pst.setString(1, traziPac.getText());
    rs=pst.executeQuery();
    tabZaLijekove.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
    e.printStackTrace(System.out);
    }}  
/////////////////////////////////////////OSVJEZAVA TABLICU ZAPOSLENIKA////////////////////////////////////////////////////////////////
private void osvjTabZap(){
try{
String sql ="SELECT kor_ime,Ime,Prezime,Dat_rod,Broj,Kontakt,razina FROM zaposlenici";
pst=conn.prepareStatement(sql);
rs=pst.executeQuery();
tabZaZap.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}}
/////////////////////////////////////////OSVJEZAVA TABLICU PACIJENTI////////////////////////////////////////////////////////////////
private void osvjTabPac(){
try{
String sql ="SELECT *FROM pacijenti";
pst=conn.prepareStatement(sql);
rs=pst.executeQuery();
tabZaPac.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception e){
e.printStackTrace(System.out);
}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        promjeniPac = new javax.swing.JButton();
        obrisiPac = new javax.swing.JButton();
        ocistiPoljaPac = new javax.swing.JButton();
        traziPac = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabZaPac = new javax.swing.JTable();
        dodajPac = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel37 = new javax.swing.JLabel();
        imePac = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        prePac = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        datPac = new javax.swing.JTextField();
        konPac = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        spolPac = new javax.swing.JComboBox();
        zdrPac = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabZaDijag = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabZaUputnice = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        opisDijagnoze = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabZaLijekove = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        traziZap = new javax.swing.JTextField();
        promjeniZap = new javax.swing.JButton();
        obrisiZap = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabZaZap = new javax.swing.JTable();
        ocistiPoljaZap = new javax.swing.JButton();
        dodajZap = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lozZap = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        imeZap = new javax.swing.JTextField();
        konZap = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        korImeZap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fkZap = new javax.swing.JComboBox();
        preZap = new javax.swing.JTextField();
        datZap = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        brojZap = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        promjeniPac.setText("Promjeni");
        promjeniPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promjeniPacActionPerformed(evt);
            }
        });

        obrisiPac.setText("Obriši");
        obrisiPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiPacActionPerformed(evt);
            }
        });

        ocistiPoljaPac.setText("Očisti");
        ocistiPoljaPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocistiPoljaPacActionPerformed(evt);
            }
        });

        traziPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traziPacActionPerformed(evt);
            }
        });
        traziPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                traziPacKeyReleased(evt);
            }
        });

        jLabel38.setText("Traži:");

        tabZaPac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabZaPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabZaPacMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabZaPac);

        dodajPac.setText("Dodaj");
        dodajPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajPacActionPerformed(evt);
            }
        });

        jLabel37.setText("Spol:");

        jLabel36.setText("Kontakt:");

        jLabel35.setText("Zdravstveni broj:");

        jLabel32.setText("Ime:");

        jLabel34.setText("Datum rođenja:");

        jLabel33.setText("Prezime:");

        spolPac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muško", "Žensko" }));

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prePac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(konPac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spolPac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datPac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zdrPac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imePac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(imePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zdrPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spolPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addContainerGap())
        );
        jLayeredPane2.setLayer(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(imePac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(prePac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(datPac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(konPac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(spolPac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(zdrPac, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(promjeniPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(obrisiPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ocistiPoljaPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dodajPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(traziPac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192)
                .addComponent(jLayeredPane2)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(traziPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addGap(18, 18, 18)
                        .addComponent(dodajPac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(promjeniPac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obrisiPac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ocistiPoljaPac))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Upravljanje pacijentima", jPanel5);

        tabZaDijag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabZaDijag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabZaDijagMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabZaDijag);

        jLabel1.setText("Dijagnoze");

        tabZaUputnice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabZaUputnice);

        jLabel2.setText("Uputnice");

        opisDijagnoze.setEditable(false);
        opisDijagnoze.setColumns(20);
        opisDijagnoze.setRows(5);
        jScrollPane5.setViewportView(opisDijagnoze);

        jLabel3.setText("Opis dijagnoze:");

        tabZaLijekove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabZaLijekove);

        jLabel4.setText("Lijekovi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel1))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Pregled pacijenta", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Pacijenti", jPanel2);

        jTabbedPane3.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel9.setText("Traži:");

        traziZap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                traziZapKeyReleased(evt);
            }
        });

        promjeniZap.setText("Promjeni");
        promjeniZap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promjeniZapActionPerformed(evt);
            }
        });

        obrisiZap.setText("Obriši");
        obrisiZap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiZapActionPerformed(evt);
            }
        });

        tabZaZap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabZaZap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabZaZapMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabZaZap);

        ocistiPoljaZap.setText("Očisti");
        ocistiPoljaZap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocistiPoljaZapActionPerformed(evt);
            }
        });

        dodajZap.setText("Dodaj");
        dodajZap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajZapActionPerformed(evt);
            }
        });

        jLabel13.setText("Broj:");

        jLabel14.setText("Kontakt:");

        jLabel11.setText("Prezime:");

        jLabel15.setText("Funkcija:");

        jLabel10.setText("Ime:");

        jLabel16.setText("Korisničko ime:");

        fkZap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sestra", "Doktor" }));

        jLabel17.setText("Lozinka:");

        jLabel12.setText("Datum rođenja:");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel15))
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(imeZap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(preZap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(datZap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(brojZap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fkZap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(konZap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(korImeZap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lozZap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imeZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(datZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brojZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(3, 3, 3)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fkZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(korImeZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lozZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lozZap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(imeZap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(konZap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(korImeZap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fkZap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(preZap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(datZap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(brojZap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(3, 3, 3)
                        .addComponent(traziZap, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dodajZap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(promjeniZap, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(obrisiZap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ocistiPoljaZap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(191, 191, 191)
                .addComponent(jLayeredPane1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(traziZap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(19, 19, 19)
                                .addComponent(dodajZap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(promjeniZap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(obrisiZap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocistiPoljaZap)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Upravljanje zaposlenicima", jPanel7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Zaposlenici", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /**/
    ////////////////////ODABIR U TABLICI PACIJENTI///////////////////////
    private void tabZaPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabZaPacMouseClicked

        try{
        int stupac=tabZaPac.getSelectedRow();
        String t_click=(tabZaPac.getModel().getValueAt(stupac, 3).toString());
        String Query="SELECT *FROM PACIJENTI WHERE Zdravstveni_broj='"+t_click+"'";
        pst=conn.prepareStatement(Query);
        rs=pst.executeQuery();
        if(rs.next()){
        
        String add1=rs.getString("Ime");
        imePac.setText(add1);
        String add2=rs.getString("Prezime");
        prePac.setText(add2);
        String add3=rs.getString("Dat_rod");
        datPac.setText(add3);
        String add4=rs.getString("Zdravstveni_broj");
        zdrPac.setText(add4);
        String add5=rs.getString("Kontakt");
        konPac.setText(add5);
        String add6=rs.getString("Spol");
        spolPac.setSelectedItem(add6);
        }
        }catch(Exception e){
            e.printStackTrace(System.out);
                    }      
    }//GEN-LAST:event_tabZaPacMouseClicked
///////////////////////////////////////////////////////DODAVANJE ZAPOSLENIKA//////////////////////////////////////////////////////
    private void dodajZapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajZapActionPerformed

        try{
            if( imeZap.getText().trim().isEmpty()  ||  preZap.getText().isEmpty()
                ||  datZap.getText().trim().isEmpty() ||  brojZap.getText().trim().isEmpty()
                || konZap.getText().trim().isEmpty()|| korImeZap.getText().trim().isEmpty()|| lozZap.getText().trim().isEmpty()  )
            {

                JOptionPane.showMessageDialog(null, "Unesite sve podatke!");
            }

            else{      
                String sql="SELECT kor_ime FROM zaposlenici";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();

                while(rs.next())
                {
                    String user = rs.getString("kor_ime");
                    if(user.equals( korImeZap.getText()))
                    { imeKorisnicko = false;
                        break; }
                    else
                    imeKorisnicko = true;
                }
                if (imeKorisnicko == true)
                {
                    String Query = "INSERT INTO zaposlenici (IME , PREZIME ,"
                    + " DAT_ROD , BROJ , KONTAKT , RAZINA,KOR_IME,LOZINKA) VALUES "
                    + "('"+ imeZap.getText()+"','"+ preZap.getText()+"' ,"
                    + " '"+ datZap.getText()+"','"+ brojZap.getText()+"','"+ konZap.getText()+"',"
                    + " '"+ fkZap.getSelectedItem()+"','"+ korImeZap.getText()+"','"+ lozZap.getText()+"' )";

                    pst.execute(Query);
                    JOptionPane.showMessageDialog(null, "Zaposlenik je dodan!");
                    osvjTabZap();
                    cistiPolja();
                }}
                if(imeKorisnicko == false)
                {
                    JOptionPane.showMessageDialog(null, "Zaposlenik već postoji");
                }
            }
            catch(SQLException e)
            {
                e.printStackTrace(System.out);
            }
            
    }//GEN-LAST:event_dodajZapActionPerformed
///////////////////////////////////////////////////////ČISTI POLJA OD PODATAKA U ZAPOSLENIM//////////////////////////////////////////////////////
    private void ocistiPoljaZapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocistiPoljaZapActionPerformed
        cistiPolja();
    }//GEN-LAST:event_ocistiPoljaZapActionPerformed

    private void cistiPolja(){
        imeZap.setText("");
        preZap.setText("");
        datZap.setText("");
        brojZap.setText("");
        konZap.setText("");
        korImeZap.setText("");
        lozZap.setText("");
}
    
///////////////////////////////////////////////////ODABIR U TABLICI ZAPOSLENICI///////////////////////
    private void tabZaZapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabZaZapMouseClicked
       try{
            int stupac=tabZaZap.getSelectedRow();
            String Tbl_click=(tabZaZap.getModel().getValueAt(stupac,0).toString());
            String sql="SELECT *FROM zaposlenici WHERE kor_ime ='"+Tbl_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){

                String add1=rs.getString("Ime");
                imeZap.setText(add1);
                String add2=rs.getString("Prezime");
                preZap.setText(add2);
                String add3=rs.getString("Dat_rod");
                datZap.setText(add3);
                String add4=rs.getString("Broj");
                brojZap.setText(add4);
                String add5=rs.getString("Kontakt");
                konZap.setText(add5);
                String add6=rs.getString("kor_ime");
                korImeZap.setText(add6);
                String add7=rs.getString("lozinka");
                lozZap.setText(add7);
                String add8=rs.getString("Razina");
                fkZap.setSelectedItem(add8);
            }

        }catch(Exception e){
            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_tabZaZapMouseClicked
/////////////////////////////////////MJENJA PODATKE ZAPOSLENIKU///////////////////////////////////////////////////////////
    private void promjeniZapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promjeniZapActionPerformed
        // TODO add your handling code here:
        try{
            if( imeZap.getText().trim().isEmpty()  ||  preZap.getText().isEmpty()
                ||  datZap.getText().trim().isEmpty() ||  brojZap.getText().trim().isEmpty()
                || konZap.getText().trim().isEmpty()|| korImeZap.getText().trim().isEmpty()|| lozZap.getText().trim().isEmpty()  )
            {

                JOptionPane.showMessageDialog(null, "Unesite sve podatke!");
            }

            else{      
            String vrj1 = imeZap.getText();
            String vrj2 = preZap.getText();
            String vrj3 = datZap.getText();
            String vrj4 = brojZap.getText();
            String vrj5 = konZap.getText();
            String vrj6 = korImeZap.getText();
            String vrj7 = lozZap.getText();
            String vrj8 = fkZap.getSelectedItem().toString();
            String Query = "UPDATE Zaposlenici SET Ime ='"+vrj1+"',Prezime ='"+vrj2+"',Dat_rod ='"+vrj3+"',"
                    + "Kontakt ='"+vrj5+"',kor_ime ='"+vrj6+"',lozinka ='"+vrj7+"',Razina ='"+vrj8+"' WHERE Broj ='"+vrj4+"' ";
            pst = conn.prepareStatement(Query);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Zaposlenik je ažuriran");
            osvjTabZap();
                }     
            }
            catch(Exception e)
            {
                e.printStackTrace(System.out);
            }
    }//GEN-LAST:event_promjeniZapActionPerformed
//////////////////////////////////TRAZI ZAP PO RADNOM BROJU//////////////////////////////////////
    private void traziZapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_traziZapKeyReleased
        // TODO add your handling code here:
        try{

            String sql="select *from zaposlenici where broj =?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, traziZap.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Ime");
                imeZap.setText(add1);
                String add2=rs.getString("Prezime");
                preZap.setText(add2);
                String add3=rs.getString("Dat_rod");
                datZap.setText(add3);
                String add4=rs.getString("Broj");
                brojZap.setText(add4);
                String add5=rs.getString("Kontakt");
                konZap.setText(add5);
                String add6=rs.getString("kor_ime");
                korImeZap.setText(add6);
                String add7=rs.getString("lozinka");
                lozZap.setText(add7);
                String add8=rs.getString("Razina");
                fkZap.setSelectedItem(add8);
            }

        }catch(Exception e){
           e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_traziZapKeyReleased
//////////////////////////////////////////DODAJ PACIJENTA//////////////////////////////////////////////////////////////
    private void dodajPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajPacActionPerformed
        
         try{
            if(imePac.getText().trim().isEmpty()  || prePac.getText().isEmpty()
                || datPac.getText().trim().isEmpty() || zdrPac.getText().trim().isEmpty()
                ||konPac.getText().trim().isEmpty()  )
            {

                JOptionPane.showMessageDialog(null, "Unesite sve podatke!");
            }
            
            
            else{

                  String sql="SELECT Zdravstveni_broj FROM pacijenti";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                 
            while(rs.next())
            {
                String user = rs.getString("Zdravstveni_broj");
                if(user.equals(zdrPac.getText()))
                { brojPac = true;
                    break; }
                else
                    brojPac = false;
            }
                if (brojPac == false)
                {
                String Query = "INSERT INTO pacijenti (IME , PREZIME ,"
                   + " DAT_ROD , ZDRAVSTVENI_BROJ , KONTAKT , SPOL) VALUES "
                + "('"+imePac.getText()+"','"+prePac.getText()+"' ,"
                + " '"+datPac.getText()+"','"+zdrPac.getText()+"','"+konPac.getText()+"',"
                + " '"+spolPac.getSelectedItem()+"' )";
                pst.execute(Query);

                JOptionPane.showMessageDialog(null, "Pacijent je dodan!");
                 osvjTabPac();

                imePac.setText(null);
               prePac.setText(null);
                datPac.setText(null);
               zdrPac.setText(null);
              konPac.setText(null);
                
            }}
            if(brojPac == true)
            {
                JOptionPane.showMessageDialog(null, "Pacijent već postoji");
            }
        }
        catch(SQLException e)
        {
            e.printStackTrace(System.out);
        } 
    }//GEN-LAST:event_dodajPacActionPerformed

///////////////////////////////////ČISTI POLJA ZA PACIJENTE/////////////////////////////////////////
    private void ocistiPoljaPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocistiPoljaPacActionPerformed
       imePac.setText("");
       prePac.setText("");
       datPac.setText("");
       zdrPac.setText("");
       konPac.setText("");
       traziPac.setText("");
    }//GEN-LAST:event_ocistiPoljaPacActionPerformed
/////////////////////////////////////MJENJA PODATKE PACIJENTIMA///////////////////////////////////////////////////////////
    private void promjeniPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promjeniPacActionPerformed
        // TODO add your handling code here:
         try{
            if( imePac.getText().trim().isEmpty()  ||  prePac.getText().isEmpty()
                ||  datPac.getText().trim().isEmpty() ||  zdrPac.getText().trim().isEmpty()
                || konPac.getText().trim().isEmpty())
            {

                JOptionPane.showMessageDialog(null, "Unesite sve podatke!");
            }

            else{      
            String vrj1 = imePac.getText();
            String vrj2 = prePac.getText();
            String vrj3 = datPac.getText();
            String vrj4 = zdrPac.getText();
            String vrj5 = konPac.getText();
            String vrj6 = spolPac.getSelectedItem().toString();
            String Query = "UPDATE Pacijenti SET Ime ='"+vrj1+"',Prezime ='"+vrj2+"',Dat_rod ='"+vrj3+"',"
                    + "Kontakt ='"+vrj5+"',spol = '"+vrj6+"' WHERE Zdravstveni_broj ='"+vrj4+"' ";
            pst = conn.prepareStatement(Query);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Pacijent je ažuriran");
            osvjTabPac();
                }     
            }
            catch(Exception e)
            {
                e.printStackTrace(System.out);
            }
        
    }//GEN-LAST:event_promjeniPacActionPerformed

        //////////////////////////////////TRAZI PAC PO ZDR BROJU//////////////////////////////////////
    private void traziPacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_traziPacKeyReleased
        // TODO add your handling code here:
        tabZaLijekove();
        tabZaDijag();
        tabZaUputnice();
        try{

            String sql="select *from pacijenti where Zdravstveni_broj =?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, traziPac.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("Ime");
                imePac.setText(add1);
                String add2=rs.getString("Prezime");
                prePac.setText(add2);
                String add3=rs.getString("Dat_rod");
                datPac.setText(add3);
                String add4=rs.getString("Zdravstveni_broj");
                zdrPac.setText(add4);
                String add5=rs.getString("Kontakt");
                konPac.setText(add5);
                String add8=rs.getString("Spol");
                spolPac.setSelectedItem(add8);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_traziPacKeyReleased
///////////////////////////////////BRIŠE ZAPOSLENIKA////////////////////////////////////
    private void obrisiZapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiZapActionPerformed
        // TODO add your handling code here:
        try{
             if( imeZap.getText().trim().isEmpty()  ||  preZap.getText().isEmpty()
                ||  datZap.getText().trim().isEmpty() ||  brojZap.getText().trim().isEmpty()
                || konZap.getText().trim().isEmpty()|| korImeZap.getText().trim().isEmpty()|| lozZap.getText().trim().isEmpty())
            {

                JOptionPane.showMessageDialog(null, "Odaberite zaposlenika!");
            }    
            else{
            int d = JOptionPane.showConfirmDialog(null,"Želite li obrisati zaposlenika?","Obavijest",JOptionPane.YES_NO_OPTION );
            if(d==0){
            String sql="delete from zaposlenici where kor_ime =?";
            pst=conn.prepareStatement(sql);
            pst.setString(1 ,korImeZap.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Zaposlenik je obrisan");
            osvjTabZap(); 
            cistiPolja();
            }
            else{
            }
               }          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_obrisiZapActionPerformed
///////////////////////////////////BRIŠE PACIJENTA////////////////////////////////////
    private void obrisiPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiPacActionPerformed
        // TODO add your handling code here:
         try{
             if(imePac.getText().trim().isEmpty()  || prePac.getText().isEmpty()
                || datPac.getText().trim().isEmpty() || zdrPac.getText().trim().isEmpty()
                ||konPac.getText().trim().isEmpty()  )
            {

                JOptionPane.showMessageDialog(null, "Unesite sve podatke!");
            }
            else{
            int d = JOptionPane.showConfirmDialog(null,"Želite li obrisati pacijenta i sve njegove podatke?","Obavijest",JOptionPane.YES_NO_OPTION );
            if(d==0){
            String sql= "DELETE FROM pacijenti WHERE Zdravstveni_broj= ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1 ,zdrPac.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Pacijent je obrisan");
            opisDijagnoze.setText("");
            imePac.setText("");
            prePac.setText("");
            datPac.setText("");
            zdrPac.setText("");
            konPac.setText("");
            traziPac.setText("");
            osvjTabPac(); 
          
            
            }
            else{
            }
               }          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_obrisiPacActionPerformed
//ISPIS DIJAGNOZE U TEXTAREA
    private void tabZaDijagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabZaDijagMouseClicked
        // TODO add your handling code here:
        try{
        int stupac=tabZaDijag.getSelectedRow();
        String t_click=(tabZaDijag.getModel().getValueAt(stupac, 0).toString());
        String sql="SELECT *FROM dijagnoze WHERE id='"+t_click+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
        
        String add1=rs.getString("Dijagnoza");
        opisDijagnoze.setText(add1);
        }
        
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
                    }
        
    }//GEN-LAST:event_tabZaDijagMouseClicked

    private void traziPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traziPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traziPacActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sestra().setVisible(true);
            }
        });
    }
 
     public boolean imeKorisnicko = true; //provjera da li postoji user pri pravljenju novog zaposlenika
     public boolean brojPac = false; //provjera da li postoji pacijent pri dodavanju
     public String provjera;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brojZap;
    private javax.swing.JTextField datPac;
    private javax.swing.JTextField datZap;
    private javax.swing.JButton dodajPac;
    private javax.swing.JButton dodajZap;
    private javax.swing.JComboBox fkZap;
    private javax.swing.JTextField imePac;
    private javax.swing.JTextField imeZap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField konPac;
    private javax.swing.JTextField konZap;
    private javax.swing.JTextField korImeZap;
    private javax.swing.JPasswordField lozZap;
    private javax.swing.JButton obrisiPac;
    private javax.swing.JButton obrisiZap;
    private javax.swing.JButton ocistiPoljaPac;
    private javax.swing.JButton ocistiPoljaZap;
    private javax.swing.JTextArea opisDijagnoze;
    private javax.swing.JTextField prePac;
    private javax.swing.JTextField preZap;
    private javax.swing.JButton promjeniPac;
    private javax.swing.JButton promjeniZap;
    private javax.swing.JComboBox spolPac;
    private javax.swing.JTable tabZaDijag;
    private javax.swing.JTable tabZaLijekove;
    private javax.swing.JTable tabZaPac;
    private javax.swing.JTable tabZaUputnice;
    private javax.swing.JTable tabZaZap;
    private javax.swing.JTextField traziPac;
    private javax.swing.JTextField traziZap;
    private javax.swing.JTextField zdrPac;
    // End of variables declaration//GEN-END:variables
}
